### ISSUE TITLE
Not working in Playnite 9

### ISSUE THREAD

**Issue by JamesFrankel** [Musiqua/QuickRatings#1]
Playnite 9 broke the compability for lot of older extensions. I guess it has to be recompiled with the new SDK, maybe?

It would be awesome if QuickRatings could be updated for Playnite 9!

**Comment by jack5github** [comment]
Bumping this because I too would like to see an easy user reviewing plugin supported in the newest Playnite.

**Comment by martin-soderberg** [comment]
Sorry for the late update regarding QuickRatings, but I have personally migrated away from Playnite and have no plans of updating the plugin for newer versions. If the plugin from @terrehbyte linked below solves the use case then great! If not, my plugin is available to fork and update.

https://github.com/terrehbyte/StarRatings/releases
